
import React from "react";
import { Sun, Users, Utensils, MapPin, VolumeX, User, Home } from "lucide-react";

import johnJayImg from "../images/johnjay.png";
import carmanImg from "../images/carman.png";
import elliotImg from "../images/elliot.png";
import weinImg from "../images/weinhall.png";
import harmonyImg from "../images/harmonyhall.png";
import w116Img from "../images/620W116th.png";
import carltonImg from "../images/carltonarms.png";
import eastCampusImg from "../images/eastcampus.png";
import schapiroImg from "../images/schapiro.png";

export const dorms = [
    {
        id: 1,
      name: "John Jay Hall",
      description: "Spacious suites with great sunlight and full kitchens...",
      rating: 4.2,
      reviews: 231,
      image: johnJayImg,
      university: "Columbia",
      universityColor: "indigo",
      amenityIcon: <Sun size={14} />,
      amenityLabel: "Sunlight",
      housing: "Corridor",
      year: "Upperclassman housing",
      amenities: ["Kitchen", "AC", "Laundry", "Common space"],
      proximity: "South Campus",
      roomType: "Singles, Doubles",
      capacity: "1-2 People",
      avgSize: "140-240 sq ft",
      detailAmenities: ["Laundry", "Campus View", "Study Lounge", "Elevator", "Floor Kitchen", "High-speed Wifi"],
      about: "A cozy dorm in the heart of campus, John Jay Hall is known for its community vibe and friendly atmosphere. Rooms have plenty of natural light and come with standard furnishing. Enjoy spacious floor lounges and close proximity to John Jay dining hall!",
    },
    {
      id: 2,
      name: "Carman Hall",
      description: "Central and lively with nice views, though thin walls...",
      rating: 4.5,
      reviews: 22,
      image: carmanImg,
      university: "Columbia",
      universityColor: "indigo",
      amenityIcon: <Users size={14} />,
      amenityLabel: "Social",
      housing: "Corridor style",
      year: "First year housing",
      amenities: ["AC", "Laundry", "Common space"],
      proximity: "On campus",
    },
    {
      id: 3,
      name: "Elliott Hall",
      description: "Apartment-style suites with big kitchens and easy access...",
      rating: 4.8,
      reviews: 212,
      image: elliotImg,
      university: "Barnard",
      universityColor: "indigo",
      amenityIcon: <Utensils size={14} />,
      amenityLabel: "Kitchen",
      housing: "Suite style",
      year: "Upperclassman housing",
      amenities: ["Kitchen", "AC", "Laundry", "Common space"],
      proximity: "2 - 5 min walk",
    },
    {
      id: 4,
      name: "Wein Hall",
      description: "Super convenient location and strong community vibes...",
      rating: 4.2,
      reviews: 38,
      image: weinImg,
      university: "Columbia",
      universityColor: "indigo",
      amenityIcon: <MapPin size={14} />,
      amenityLabel: "Location",
      housing: "Corridor style",
      year: "First year housing",
      amenities: ["AC", "Laundry", "Common space"],
      proximity: "On campus",
    },
    {
      id: 5,
      name: "Harmony Hall",
      description: "Quiet suites with generous living space and a mature crowd...",
      rating: 3.6,
      reviews: 245,
      image: harmonyImg,
      university: "Columbia",
      universityColor: "indigo",
      amenityIcon: <VolumeX size={14} />,
      amenityLabel: "Quiet",
      housing: "Suite style",
      year: "Upperclassman housing",
      amenities: ["Kitchen", "AC", "Laundry", "Cleaning service", "Common space"],
      proximity: "2 - 5 min walk",
    },
    {
      id: 6,
      name: "620 W 116th St",
      description: "Quiet singles and central location perfect for studying...",
      rating: 3.8,
      reviews: 22,
      image: w116Img,
      university: "Barnard",
      universityColor: "indigo",
      amenityIcon: <User size={14} />,
      amenityLabel: "Singles",
      housing: "Corridor style",
      year: "Upperclassman housing",
      amenities: ["AC", "Laundry"],
      proximity: "5 - 10 min walk",
    },
    {
      id: 7,
      name: "Carlton Arms",
      description: "Super convenient location and strong community vibes...",
      rating: 4.2,
      reviews: 212,
      image: carltonImg,
      university: "Columbia",
      universityColor: "indigo",
      amenityIcon: <Home size={14} />,
      amenityLabel: "Spacious",
      housing: "Suite style",
      year: "Upperclassman housing",
      amenities: ["Kitchen", "AC", "Laundry", "Common space"],
      proximity: "2 - 5 min walk",
    },
    {
      id: 8,
      name: "East Campus",
      description: "Quiet suites with generous living space and a mature crowd...",
      rating: 3.4,
      reviews: 231,
      image: eastCampusImg,
      university: "Columbia",
      universityColor: "indigo",
      amenityIcon: <Utensils size={14} />,
      amenityLabel: "Kitchen",
      housing: "Suite style",
      year: "Upperclassman housing",
      amenities: ["Kitchen", "AC", "Laundry", "Common space"],
      proximity: "On campus",
    },
    {
      id: 9,
      name: "Schapiro Hall",
      description: "Quiet singles and central location perfect for studying...",
      rating: 3.3,
      reviews: 212,
      image: schapiroImg,
      university: "Columbia",
      universityColor: "indigo",
      amenityIcon: <User size={14} />,
      amenityLabel: "Singles",
      housing: "Corridor style",
      year: "First year housing",
      amenities: ["AC", "Laundry", "Common space"],
      proximity: "On campus",
    },
];

